
const commonContent = {
    objective: {
        title: "1. Objective",
    },
    playersAndTurns: {
        title: "2. Players & Turn Order",
    },
    board: {
        title: "3. The Board",
    },
    setup: {
        title: "4. Piece Setup",
    },
    movement: {
        title: "5. Piece Movement Rules",
    },
    endGame: {
        title: "6. Check, Checkmate, Stalemate & Draws",
    },
    promotion: {
        title: "7. Pawn Promotion Zones",
    },
    values: {
        title: "8. Piece Values (for captures)",
    },
    rating: {
        title: "9. Rating System (Elo)",
    }
};

export const rulesData = {
    en: {
        title: "Game Rules",
        sections: [
            { title: commonContent.objective.title, content: "<p>The objective of the game is to eliminate all opponents by checkmating them. The last player remaining on the board is declared the winner.</p>" },
            { title: commonContent.playersAndTurns.title, content: "<ul><li><strong>Players:</strong> There are three players: White (left), Black (right), and Gray (top).</li><li><strong>Turn Order:</strong> White moves first. Play then proceeds counter-clockwise: White → Black → Gray.</li></ul>" },
            { title: commonContent.board.title, content: "<ul><li>The board is triangular.</li><li>The central cells (the 'fortress') are marked in black and are impassable. Pieces cannot move through or onto these cells.</li></ul>" },
            { title: commonContent.setup.title, content: "<ul><li><strong>Pawns:</strong> Start the game in fixed, predetermined positions.</li><li><strong>Other Pieces:</strong> Players take turns placing their remaining pieces (King, Queen, Rooks, Bishop, Knight) within their designated starting zones.</li></ul>" },
            { title: commonContent.movement.title, content: "<ul><li><strong>King, Queen, Rook, Knight:</strong> These pieces move according to the standard rules of classical chess.</li><li><strong>King Proximity:</strong> A King cannot move to a square adjacent to another King.</li><li><strong>Pawn:</strong> Has unique movement capabilities:<ul><li><strong>Movement (Non-capture):</strong> Can move one square forward, sideways, or backward. A pawn's first move can be one or two squares forward.</li><li><strong>Capture:</strong> Captures an opponent's piece by moving one square diagonally in any direction (forwards or backwards).</li></ul></li><li><strong>Bishop:</strong><ul><li><strong>Standard Move:</strong> Moves any number of vacant squares diagonally, as in classical chess.</li><li><strong>Special Move (Diagonal Switch):</strong> A Bishop can move one square orthogonally (forward, backward, or sideways) to an empty square to switch to a different-colored set of diagonals. This move cannot be used to deliver check.</li><li><strong>Special Move Cooldown:</strong> After making a special move to switch diagonals, the Bishop must make at least one standard diagonal move before it is allowed to switch diagonals again.</li></ul></li></ul>" },
            { title: commonContent.endGame.title, content: "<ul><li><strong>Check:</strong> A position where a King is under attack by an opponent's piece. The player must make a move to get their King out of check.</li><li><strong>Duel (Single Check):</strong> If a player's move checks a single opponent, it initiates a 'duel'. The turn passes to the defender, who must escape the check. After the defender moves, the original attacker gets a bonus move. After the attacker's bonus move, the duel ends and play proceeds normally (unless the bonus move started a new duel).</li><li><strong>Multiple Checks:</strong> If a player's move places two opponents in check simultaneously, no duel occurs. The turn proceeds normally in counter-clockwise order.</li><li><strong>Checkmate:</strong> A situation where a player's King is in check, and there are no legal moves to escape the check. A checkmated player is eliminated, and all of their pieces are removed from the board.</li><li><strong>Stalemate:</strong> A situation where a player is not in check but has no legal moves. A stalemated player is also eliminated from the game.</li><li><strong>Draw by Insufficient Material:</strong> The game is declared a draw if a position is reached where no player can force a checkmate. This occurs under conditions such as:<ul><li>Only the Kings remain on the board.</li><li>Only Kings and one Knight (total) remain on the board.</li><li>Only Kings and one Bishop (total) remain on the board.</li></ul></li><li>The game continues until only one player remains or a draw is declared.</li></ul>" },
            { title: commonContent.promotion.title, content: "<p>When a pawn reaches an opponent's promotion zone, it must be immediately promoted to a Queen, Rook, Bishop, or Knight of the same color. These zones are marked with small colored circles when empty.</p>" },
            { title: commonContent.values.title, content: "<ul><li>Pawn: 1 point</li><li>Knight: 3 points</li><li>Bishop: 3 points</li><li>Rook: 5 points</li><li>Queen: 9 points</li></ul>" },
            { title: commonContent.rating.title, content: "<p>The game uses a modified Elo system for 3 players. <strong>Winner takes all:</strong> The winner gains rating points calculated against both losing opponents. The losers lose rating points as if they lost a match against the winner. If you leave a ranked match early, it counts as a loss against all remaining players.</p>" },
        ]
    },
    ru: {
        title: "Правила Игры",
        sections: [
            { title: "1. Цель Игры", content: "<p>Цель игры — устранить всех противников, поставив им шах и мат. Последний игрок, оставшийся на доске, объявляется победителем.</p>" },
            { title: "2. Игроки и Порядок Ходов", content: "<ul><li><strong>Игроки:</strong> В игре участвуют три игрока — Белые (слева), Чёрные (справа) и Серые (сверху).</li><li><strong>Порядок ходов:</strong> Первыми ходят Белые. Далее ход передаётся против часовой стрелки: Белые → Чёрные → Серые.</li></ul>" },
            { title: "3. Игровая Доска", content: "<ul><li>Доска имеет треугольную форму.</li><li>Центральные ячейки ('крепость') отмечены чёрным цветом и являются непроходимыми. Фигуры не могут ходить через них или останавливаться на них.</li></ul>" },
            { title: "4. Расстановка Фигур", content: "<ul><li><strong>Пешки:</strong> Начинают игру на заранее определённых позициях.</li><li><strong>Остальные фигуры:</strong> Игроки по очереди расставляют свои фигуры (Король, Ферзь, Ладьи, Слон, Конь) в пределах своей стартовой зоны.</li></ul>" },
            { title: "5. Правила Ходов Фигур", content: "<ul><li><strong>Король, Ферзь, Ладья, Конь:</strong> Ходят по стандартным правилам классических шахмат.</li><li><strong>Близость Королей:</strong> Король не может ходить на клетку, соседнюю с другим Королём.</li><li><strong>Пешка:</strong> Обладает уникальными возможностями:<ul><li><strong>Движение (без взятия):</strong> Может двигаться на одну клетку вперёд, вбок или назад. Первый ход пешки может быть на одну или две клетки вперёд.</li><li><strong>Взятие:</strong> Бьёт фигуры противника по диагонали на одну клетку в любом направлении (вперёд или назад).</li></ul></li><li><strong>Слон:</strong><ul><li><strong>Основной ход:</strong> Двигается по диагоналям на любое количество свободных клеток.</li><li><strong>Специальный ход (Смена диагонали):</strong> Слон может сделать ход на одну пустую клетку по прямой (вперёд, назад или вбок), чтобы перейти на диагональ другого цвета. Этот ход не может быть использован для объявления шаха.</li><li><strong>Ограничение специального хода:</strong> После того как слон использовал специальный ход для смены диагонали, он обязан сделать хотя бы один диагональный ход, прежде чем сможет снова сменить диагональ.</li></ul></li></ul>" },
            { title: "6. Шах, Мат, Пат и Ничья", content: "<ul><li><strong>Шах:</strong> Позиция, когда Король атакован фигурой противника. Игрок обязан увести Короля из-под шаха.</li><li><strong>Дуэль (Одиночный шах):</strong> Если ход игрока ставит шах одному противнику, начинается 'дуэль'. Ход переходит к защищающемуся, который обязан уйти из-под шаха. После хода защищающегося атакующий получает бонусный ход. После бонусного хода атакующего дуэль завершается, и игра продолжается в обычном порядке (если только бонусный ход не начал новую дуэль).</li><li><strong>Двойной Шах:</strong> Если ход игрока ставит шах сразу двум противникам, дуэль не происходит. Ход переходит к следующему игроку в обычном порядке.</li><li><strong>Мат:</strong> Ситуация, когда Королю поставлен шах, и у игрока нет ни одного хода, чтобы его избежать. Игрок, получивший мат, выбывает из игры.</li><li><strong>Пат:</strong> Ситуация, когда у игрока нет ни одного возможного хода, но его Король не находится под шахом. Игрок в такой ситуации также выбывает из игры.</li><li><strong>Ничья из-за недостатка фигур:</strong> Игра объявляется вничью, если на доске не осталось достаточно фигур для постановки мата. Например:<ul><li>На доске остались только Короли.</li><li>На доске остались только Короли и один Конь (в сумме).</li><li>На доске остались только Короли и один Слон (в сумме).</li></ul></li><li>Игра продолжается, пока не останется один игрок или не будет объявлена ничья.</li></ul>" },
            { title: "7. Зоны Превращения Пешек", content: "<p>Когда пешка достигает зоны превращения противника, она должна быть немедленно заменена на Ферзя, Ладью, Слона или Коня того же цвета. Эти зоны отмечены цветными кружками, когда они пусты.</p>" },
            { title: "8. Ценность Фигур (за взятие)", content: "<ul><li>Пешка: 1 очко</li><li>Конь: 3 очка</li><li>Слон: 3 очка</li><li>Ладья: 5 очков</li><li>Ферзь: 9 очков</li></ul>" },
            { title: "9. Рейтинг (Elo)", content: "<p>В игре используется система Elo, адаптированная для 3 игроков. <strong>Победитель получает всё:</strong> Победитель получает очки рейтинга от обоих проигравших. Проигравшие теряют очки так, как если бы они проиграли дуэль победителю. Если вы покидаете рейтинговый матч досрочно, это засчитывается как поражение всем оставшимся игрокам.</p>" },
        ]
    },
    de: {
        title: "Spielregeln",
        sections: [
            { title: "1. Ziel des Spiels", content: "<p>Das Ziel ist es, alle Gegner durch Schachmatt zu eliminieren. Der letzte Spieler auf dem Brett gewinnt.</p>" },
            { title: "2. Spieler & Zugreihenfolge", content: "<ul><li><strong>Spieler:</strong> Weiß (links), Schwarz (rechts), und Grau (oben).</li><li><strong>Zugreihenfolge:</strong> Weiß → Schwarz → Grau.</li></ul>" },
            { title: "3. Das Spielbrett", content: "<ul><li>Das Brett ist dreieckig.</li><li>Die zentralen Felder ('Festung') sind unpassierbar.</li></ul>" },
            { title: "4. Aufstellung", content: "<ul><li><strong>Bauern:</strong> Feste Startpositionen.</li><li><strong>Andere Figuren:</strong> Spieler setzen ihre restlichen Figuren in ihren Startzonen.</li></ul>" },
            { title: "5. Zugregeln", content: "<ul><li><strong>König, Dame, Turm, Springer:</strong> Standardregeln.</li><li><strong>Königsnähe:</strong> Ein König darf kein Feld betreten, das an einen anderen König angrenzt.</li><li><strong>Bauer:</strong><ul><li><strong>Bewegung:</strong> Ein Feld vorwärts, seitwärts oder rückwärts. Erster Zug: ein oder zwei Felder vorwärts.</li><li><strong>Schlagen:</strong> Ein Feld diagonal in jede Richtung.</li></ul></li><li><strong>Läufer:</strong><ul><li><strong>Standardzug:</strong> Diagonal.</li><li><strong>Sonderzug:</strong> Ein Feld orthogonal auf ein leeres Feld, um die Diagonalenfarbe zu wechseln. Dieser Zug darf keinen Schach bieten.</li><li><strong>Abklingzeit:</strong> Nach einem Sonderzug muss ein normaler Diagonalzug folgen.</li></ul></li></ul>" },
            { title: "6. Schach, Matt, Patt & Remis", content: "<ul><li><strong>Schach:</strong> Ein König ist angegriffen.</li><li><strong>Duell (Einfaches Schach):</strong> Ein Zug, der einen einzelnen Gegner schach setzt, löst ein 'Duell' aus. Der Zug geht an den Verteidiger, der aus dem Schach entkommen muss. Nachdem der Verteidiger gezogen hat, erhält der ursprüngliche Angreifer einen Bonus-Zug. Nach dem Bonus-Zug des Angreifers endet das Duell und das Spiel geht normal weiter (es sei denn, der Bonus-Zug hat ein neues Duell begonnen).</li><li><strong>Mehrfaches Schach:</strong> Ein Zug, der zwei Gegner gleichzeitig schach setzt, löst kein Duell aus. Die Zugreihenfolge geht normal weiter.</li><li><strong>Schachmatt:</strong> Ein Spieler, der schachmatt gesetzt ist, scheidet aus.</li><li><strong>Patt:</strong> Ein Spieler im Patt scheidet ebenfalls aus.</li><li><strong>Remis durch unzureichendes Material:</strong> Das Spiel ist unentschieden, wenn kein Matt mehr erzwungen werden kann, z.B.:<ul><li>Nur noch Könige auf dem Brett.</li><li>Nur noch Könige und ein Springer (insgesamt).</li><li>Nur noch Könige und ein Läufer (insgesamt).</li></ul></li><li>Das Spiel endet, wenn nur noch ein Spieler übrig ist oder es remis ist.</li></ul>" },
            { title: "7. Bauernumwandlung", content: "<p>Wenn ein Bauer eine gegnerische Umwandlungszone erreicht, wird er zu einer Dame, einem Turm, Läufer oder Springer. Die Zonen sind durch farbige Kreise markiert.</p>" },
            { title: "8. Figurenwerte", content: "<ul><li>Bauer: 1 Punkt</li><li>Springer: 3 Punkte</li><li>Läufer: 3 Punkte</li><li>Turm: 5 Punkte</li><li>Dame: 9 Punkte</li></ul>" },
            { title: "9. Bewertungssystem (Elo)", content: "<p>Das Spiel verwendet ein angepasstes Elo-System. <strong>Der Gewinner bekommt alles:</strong> Der Sieger erhält Punkte von beiden Verlierern. Die Verlierer verlieren Punkte an den Sieger. Das vorzeitige Verlassen eines gewerteten Spiels zählt als Niederlage gegen alle verbleibenden Spieler.</p>" },
        ]
    },
    fr: {
        title: "Règles du Jeu",
        sections: [
            { title: "1. Objectif", content: "<p>L'objectif est d'éliminer tous les adversaires par échec et mat. Le dernier joueur restant gagne.</p>" },
            { title: "2. Joueurs & Ordre", content: "<ul><li><strong>Joueurs :</strong> Blanc (gauche), Noir (droite), et Gris (haut).</li><li><strong>Ordre :</strong> Blanc → Noir → Gris.</li></ul>" },
            { title: "3. L'Échiquier", content: "<ul><li>L'échiquier est triangulaire.</li><li>Les cases centrales (la 'forteresse') sont infranchissables.</li></ul>" },
            { title: "4. Mise en Place", content: "<ul><li><strong>Pions :</strong> Positions de départ fixes.</li><li><strong>Autres pièces :</strong> Les joueurs placent leurs pièces restantes dans leurs zones de départ.</li></ul>" },
            { title: "5. Mouvement", content: "<ul><li><strong>Roi, Dame, Tour, Cavalier :</strong> Règles standard.</li><li><strong>Proximité des Rois :</strong> Un Roi ne peut pas se déplacer sur une case adjacente à un autre Roi.</li><li><strong>Pion :</strong><ul><li><strong>Mouvement :</strong> Une case en avant, sur le côté ou en arrière. Premier coup : une ou deux cases en avant.</li><li><strong>Capture :</strong> Une case en diagonale dans n'importe quelle direction.</li></ul></li><li><strong>Fou :</strong><ul><li><strong>Mouvement standard :</strong> En diagonale.</li><li><strong>Mouvement spécial :</strong> Une case orthogonalement sur une case vide pour changer la couleur des diagonales. Ce coup ne peut pas mettre en échec.</li><li><strong>Restriction :</strong> Après un mouvement spécial, un mouvement diagonal normal doit suivre.</li></ul></li></ul>" },
            { title: "6. Échec, Mat, Pat & Nulle", content: "<ul><li><strong>Échec :</strong> Un Roi est attaqué.</li><li><strong>Duel (Échec simple) :</strong> Un coup qui met en échec un seul adversaire déclenche un 'duel'. Le tour passe au défenseur, qui doit parer l'échec. Après le coup du défenseur, l'attaquant initial obtient un coup bonus. Après le coup bonus de l'attaquant, le duel se termine et le jeu se poursuit normalement (à moins que le coup bonus n'ait déclenché un nouveau duel).</li><li><strong>Échecs multiples :</strong> Un coup qui met en échec deux adversaires simultanément ne déclenche pas de duel. Le tour se poursuit normalement.</li><li><strong>Échec et Mat :</strong> Un joueur maté est éliminé.</li><li><strong>Pat :</strong> Un joueur en position de pat est également éliminé.</li><li><strong>Nulle par matériel insuffisant :</strong> La partie est nulle si aucun mat ne peut être forcé. Par exemple :<ul><li>Seulement les Rois restent.</li><li>Seulement les Rois et un Cavalier (au total) restent.</li><li>Seulement les Rois et un Fou (au total) restent.</li></ul></li><li>Le jeu se termine lorsqu'un seul joueur reste ou que la partie est nulle.</li></ul>" },
            { title: "7. Promotion", content: "<p>Un pion atteignant une zone de promotion adverse est promu en Dame, Tour, Fou ou Cavalier. Les zones sont marquées par des cercles de couleur.</p>" },
            { title: "8. Valeur des Pièces", content: "<ul><li>Pion : 1 point</li><li>Cavalier : 3 points</li><li>Fou : 3 points</li><li>Tour : 5 points</li><li>Dame : 9 points</li></ul>" },
            { title: "9. Système de Classement (Elo)", content: "<p>Le jeu utilise un système Elo adapté. <strong>Le gagnant remporte tout :</strong> Le vainqueur gagne des points contre les deux perdants. Les perdants perdent des points au profit du vainqueur. Quitter un match classé compte comme une défaite contre tous les joueurs restants.</p>" },
        ]
    },
    es: {
        title: "Reglas del Juego",
        sections: [
            { title: "1. Objetivo", content: "<p>El objetivo es eliminar a todos los oponentes mediante jaque mate. El último jugador en pie gana.</p>" },
            { title: "2. Jugadores y Turno", content: "<ul><li><strong>Jugadores:</strong> Blanco (izquierda), Negro (derecha) y Gris (arriba).</li><li><strong>Orden:</strong> Blanco → Negro → Gris.</li></ul>" },
            { title: "3. El Tablero", content: "<ul><li>El tablero es triangular.</li><li>Las casillas centrales (la 'fortaleza') son intransitables.</li></ul>" },
            { title: "4. Colocación", content: "<ul><li><strong>Peones:</strong> Posiciones de inicio fijas.</li><li><strong>Otras piezas:</strong> Los jugadores colocan sus piezas restantes en sus zonas de inicio.</li></ul>" },
            { title: "5. Movimiento", content: "<ul><li><strong>Rey, Dama, Torre, Caballo:</strong> Reglas estándar.</li><li><strong>Proximidad de Reyes:</strong> Un Rey no puede moverse a una casilla adyacente a otro Rey.</li><li><strong>Peón:</strong><ul><li><strong>Movimiento:</strong> Una casilla adelante, a los lados o atrás. Primer movimiento: una o dos casillas adelante.</li><li><strong>Captura:</strong> Una casilla en diagonal en cualquier dirección.</li></ul></li><li><strong>Alfil:</strong><ul><li><strong>Movimiento estándar:</strong> Diagonalmente.</li><li><strong>Movimiento especial:</strong> Una casilla ortogonal a una casilla vacía para cambiar de color de diagonal. Este movimiento no puede dar jaque.</li><li><strong>Restricción:</strong> Después de un movimiento especial, debe seguir un movimiento diagonal normal.</li></ul></li></ul>" },
            { title: "6. Jaque, Mate, Ahogado y Tablas", content: "<ul><li><strong>Jaque:</strong> Un Rey está siendo atacado.</li><li><strong>Duelo (Jaque simple):</strong> Un movimiento que da jaque a un solo oponente inicia un 'duelo'. El turno pasa al defensor, que debe escapar del jaque. Después de que el defensor se mueva, el atacante original obtiene un movimiento extra. Después del movimiento extra del atacante, el duelo termina y el juego continúa con normalidad (a menos que el movimiento extra haya iniciado un nuevo duelo).</li><li><strong>Jaques múltiples:</strong> Un movimiento que da jaque a dos oponentes a la vez no inicia un duelo. El turno procede normalmente.</li><li><strong>Jaque Mate:</strong> Un jugador que recibe mate es eliminado.</li><li><strong>Ahogado:</strong> Un jugador ahogado también es eliminado.</li><li><strong>Tablas por material insuficiente:</strong> La partida es un empate si no se puede forzar un jaque mate. Por ejemplo:<ul><li>Solo quedan los Reyes.</li><li>Solo quedan los Reyes y un Caballo (en total).</li><li>Solo quedan los Reyes y un Alfil (en total).</li></ul></li><li>El juego termina cuando solo queda un jugador o hay tablas.</li></ul>" },
            { title: "7. Promoción", content: "<p>Un peón que llega a una zona de promoción del oponente se promociona a Dama, Torre, Alfil o Caballo. Las zonas están marcadas con círculos de colores.</p>" },
            { title: "8. Valor de las Piezas", content: "<ul><li>Peón: 1 punto</li><li>Caballo: 3 puntos</li><li>Alfil: 3 puntos</li><li>Torre: 5 puntos</li><li>Dama: 9 puntos</li></ul>" },
            { title: "9. Sistema de Clasificación (Elo)", content: "<p>El juego utiliza un sistema Elo adaptado. <strong>El ganador se lo lleva todo:</strong> El ganador obtiene puntos de ambos perdedores. Los perdedores pierden puntos ante el ganador. Abandonar una partida clasificada cuenta como una derrota contra todos los jugadores restantes.</p>" },
        ]
    },
    it: {
        title: "Regole del Gioco",
        sections: [
            { title: "1. Obiettivo", content: "<p>L'obiettivo è eliminare tutti gli avversari con scacco matto. L'ultimo giocatore rimasto vince.</p>" },
            { title: "2. Giocatori e Turno", content: "<ul><li><strong>Giocatori:</strong> Bianco (sinistra), Nero (destra) e Grigio (in alto).</li><li><strong>Turno:</strong> Bianco → Nero → Grigio.</li></ul>" },
            { title: "3. Scacchiera", content: "<ul><li>La scacchiera è triangolare.</li><li>Le caselle centrali (la 'fortezza') non sono attraversabili.</li></ul>" },
            { title: "4. Setup", content: "<ul><li><strong>Pedoni:</strong> Posizioni di partenza fisse.</li><li><strong>Altri pezzi:</strong> I giocatori posizionano i pezzi rimanenti nelle loro zone di partenza.</li></ul>" },
            { title: "5. Movimiento", content: "<ul><li><strong>Re, Regina, Torre, Cavallo:</strong> Regole standard.</li><li><strong>Vicinanza dei Re:</strong> Un Re non può muoversi in una casa adiacente a un altro Re.</li><li><strong>Pedone:</strong><ul><li><strong>Movimento:</strong> Una casa avanti, di lato o indietro. Prima mossa: una o due case avanti.</li><li><strong>Cattura:</strong> Una casa in diagonale in qualsiasi direzione.</li></ul></li><li><strong>Alfiere:</strong><ul><li><strong>Mossa standard:</strong> In diagonale.</li><li><strong>Mossa speciale:</strong> Una casa ortogonale in una casa vuota per cambiare il colore della diagonale. Questa mossa non può dare scacco.</li><li><strong>Restrizione:</strong> Dopo una mossa speciale, deve seguire una mossa diagonale normale.</li></ul></li></ul>" },
            { title: "6. Scacco, Matto, Stallo e Patta", content: "<ul><li><strong>Scacco:</strong> Un Re è sotto attacco.</li><li><strong>Duello (Scacco singolo):</strong> Una mossa che dà scacco a un singolo avversario inizia un 'duello'. Il turno passa al difensore, che deve sfuggire allo scacco. Dopo la mossa del difensore, l'attaccante originale ottiene una mossa bonus. Dopo la mossa bonus dell'attaccante, il duello termina e il gioco procede normalmente (a meno che la mossa bonus non abbia iniziato un nuovo duello).</li><li><strong>Scacchi multipli:</strong> Una mossa che dà scacco a due avversari contemporaneamente non inizia un duello. Il turno procede normalmente.</li><li><strong>Scacco Matto:</strong> Un giocatore che subisce scacco matto è eliminato.</li><li><strong>Stallo:</strong> Anche un giocatore in stallo è eliminato.</li><li><strong>Patta per materiale insufficiente:</strong> La partita è patta se nessuno può forzare lo scacco matto. Ad esempio:<ul><li>Rimangono solo i Re.</li><li>Rimangono solo i Re e un Cavallo (in totale).</li><li>Rimangono solo i Re e un Alfiere (in totale).</li></ul></li><li>Il gioco termina quando rimane un solo giocatore o è patta.</li></ul>" },
            { title: "7. Promozione", content: "<p>Un pedone che raggiunge una zona di promozione avversaria viene promosso a Regina, Torre, Alfiere o Cavallo. Le zone sono indicate da cerchi colorati.</p>" },
            { title: "8. Valore dei Pezzi", content: "<ul><li>Pedone: 1 punto</li><li>Cavallo: 3 punti</li><li>Alfiere: 3 punti</li><li>Torre: 5 punti</li><li>Regina: 9 punti</li></ul>" },
            { title: "9. Sistema di Valutazione (Elo)", content: "<p>Il gioco utilizza un sistema Elo adattato. <strong>Il vincitore prende tutto:</strong> Il vincitore guadagna punti da entrambi i perdenti. I perdenti perdono punti contro il vincitore. Abbandonare una partita classificata conta come una sconfitta contro tutti i giocatori rimanenti.</p>" },
        ]
    }
};
