const commonContent = {
    objective: {
        title: "1. Objective",
    },
    playersAndTurns: {
        title: "2. Players & Turn Order",
    },
    board: {
        title: "3. The Board",
    },
    setup: {
        title: "4. Piece Setup",
    },
    movement: {
        title: "5. Piece Movement Rules",
    },
    endGame: {
        title: "6. Check, Checkmate & Stalemate",
    },
    promotion: {
        title: "7. Pawn Promotion Zones",
    },
    values: {
        title: "8. Piece Values (for captures)",
    },
};

export const rulesData = {
    en: {
        title: "Game Rules",
        sections: [
            { title: commonContent.objective.title, content: "<p>The objective of the game is to eliminate all opponents by checkmating them. The last player remaining on the board is declared the winner.</p>" },
            { title: commonContent.playersAndTurns.title, content: "<ul><li><strong>Players:</strong> There are three players: White (left), Black (right), and Gray (top).</li><li><strong>Turn Order:</strong> White moves first. Play then proceeds counter-clockwise: White → Black → Gray.</li></ul>" },
            { title: commonContent.board.title, content: "<ul><li>The board is triangular.</li><li>The central cells (the 'fortress') are marked in black and are impassable. Pieces cannot move through or onto these cells.</li></ul>" },
            { title: commonContent.setup.title, content: "<ul><li><strong>Pawns:</strong> Start the game in fixed, predetermined positions.</li><li><strong>Other Pieces:</strong> Players take turns placing their remaining pieces (King, Queen, Rooks, Bishop, Knight) within their designated starting zones.</li></ul>" },
            { title: commonContent.movement.title, content: "<ul><li><strong>King, Queen, Rook, Knight:</strong> These pieces move according to the standard rules of classical chess.</li><li><strong>Pawn:</strong> Has unique movement capabilities:<ul><li><strong>Movement (Non-capture):</strong> Can move one square forward, sideways, or backward. A pawn's first move can be one or two squares forward.</li><li><strong>Capture:</strong> Captures an opponent's piece by moving one square diagonally in any direction (forwards or backwards).</li><li><strong>Promotion:</strong> When a pawn reaches an opponent's promotion zone, it must be immediately promoted to a Queen, Rook, Bishop, or Knight of the same color.</li></ul></li><li><strong>Bishop:</strong><ul><li><strong>Standard Move:</strong> Moves any number of vacant squares diagonally, as in classical chess.</li><li><strong>Special Move (Diagonal Switch):</strong> A Bishop can move one square orthogonally (forward, backward, or sideways) to switch to a different-colored set of diagonals.</li><li><strong>Special Move Cooldown:</strong> After making a special move to switch diagonals, the Bishop must make at least one standard diagonal move before it is allowed to switch diagonals again.</li></ul></li></ul>" },
            { title: commonContent.endGame.title, content: "<ul><li><strong>Check:</strong> A position where a King is under attack by an opponent's piece. The player must make a move to get their King out of check.</li><li><strong>Checkmate:</strong> A situation where a player's King is in check, and there are no legal moves to escape the check. A checkmated player is eliminated, and all of their pieces are removed from the board.</li><li><strong>Stalemate:</strong> A situation where a player is not in check but has no legal moves. A stalemated player is also eliminated from the game.</li><li>The game continues until only one player remains.</li></ul>" },
            { title: commonContent.promotion.title, content: "<p>There are special cells on the board for pawn promotion. When a promotion cell is empty, it is marked with a small colored circle corresponding to the color of the player whose pawn can promote on that square.</p>" },
            { title: commonContent.values.title, content: "<ul><li>Pawn: 1 point</li><li>Knight: 3 points</li><li>Bishop: 3 points</li><li>Rook: 5 points</li><li>Queen: 9 points</li></ul>" },
        ]
    },
    ru: {
        title: "Правила Игры",
        sections: [
            { title: "1. Общая Цель", content: "<p>Цель игры — устранить всех противников, поставив им шах и мат. Последний игрок, оставшийся на доске, объявляется победителем.</p>" },
            { title: "2. Игроки и Порядок Ходов", content: "<ul><li><strong>Игроки:</strong> В игре участвуют три игрока — Белые (слева), Чёрные (справа) и Серые (сверху).</li><li><strong>Порядок ходов:</strong> Первыми ходят Белые. Далее ход передаётся против часовой стрелки: Белые → Чёрные → Серые.</li></ul>" },
            { title: "3. Игровая Доска", content: "<ul><li>Доска имеет треугольную форму.</li><li>Центральные ячейки ('крепость') отмечены чёрным цветом и являются непроходимыми. Фигуры не могут ходить через них или останавливаться на них.</li></ul>" },
            { title: "4. Расстановка Фигур", content: "<ul><li><strong>Пешки:</strong> Начинают игру на заранее определённых позициях.</li><li><strong>Остальные фигуры:</strong> Игроки по очереди расставляют свои фигуры (Король, Ферзь, Ладьи, Слон, Конь) в пределах своей стартовой зоны.</li></ul>" },
            { title: "5. Правила Ходов Фигур", content: "<ul><li><strong>Король, Ферзь, Ладья, Конь:</strong> Ходят по стандартным правилам классических шахмат.</li><li><strong>Пешка:</strong> Обладает уникальными возможностями:<ul><li><strong>Движение (без взятия):</strong> Может двигаться на одну клетку вперёд, вбок или назад. Первый ход пешки может быть на одну или две клетки вперёд.</li><li><strong>Взятие:</strong> Бьёт фигуры противника по диагонали на одну клетку в любом направлении (вперёд или назад).</li><li><strong>Превращение:</strong> Когда пешка достигает одной из клеток зоны превращения противника, она должна быть немедленно заменена на Ферзя, Ладью, Слона или Коня того же цвета.</li></ul></li><li><strong>Слон:</strong><ul><li><strong>Основной ход:</strong> Двигается по диагоналям на любое количество свободных клеток, как в классических шахматах.</li><li><strong>Специальный ход (Смена диагонали):</strong> Слон может сделать ход на одну клетку по прямой (вперёд, назад или вбок), чтобы перейти на диагональ другого цвета.</li><li><strong>Ограничение специального хода:</strong> После того как слон использовал специальный ход для смены диагонали, он обязан сделать хотя бы один диагональный ход, прежде чем сможет снова сменить диагональ.</li></ul></li></ul>" },
            { title: "6. Шах, Мат и Пат", content: "<ul><li><strong>Шах:</strong> Позиция, когда Король атакован фигурой противника. Игрок обязан увести Короля из-под шаха.</li><li><strong>Мат:</strong> Ситуация, когда Королю поставлен шах, и у игрока нет ни одного хода, чтобы его избежать. Игрок, получивший мат, выбывает из игры, а все его фигуры убираются с доски.</li><li><strong>Пат:</strong> Ситуация, когда у игрока нет ни одного возможного хода, но его Король не находится под шахом. Игрок, оказавшийся в такой ситуации, также выбывает из игры.</li><li>Игра продолжается до тех пор, пока на доске не останется только один игрок.</li></ul>" },
            { title: "7. Зоны Превращения Пешек", content: "<p>На доске есть специальные клетки для превращения пешек. Когда клетка в такой зоне пуста, она отмечена маленьким цветным кружком, который соответствует цвету игрока, чья пешка может на ней превратиться.</p>" },
            { title: "8. Ценность Фигур (за взятие)", content: "<ul><li>Пешка: 1 очко</li><li>Конь: 3 очка</li><li>Слон: 3 очка</li><li>Ладья: 5 очков</li><li>Ферзь: 9 очков</li></ul>" },
        ]
    },
    de: {
        title: "Spielregeln",
        sections: [
            { title: "1. Ziel des Spiels", content: "<p>Das Ziel des Spiels ist es, alle Gegner durch Schachmatt zu eliminieren. Der letzte verbleibende Spieler auf dem Brett wird zum Sieger erklärt.</p>" },
            { title: "2. Spieler & Zugreihenfolge", content: "<ul><li><strong>Spieler:</strong> Es gibt drei Spieler: Weiß (links), Schwarz (rechts) und Grau (oben).</li><li><strong>Zugreihenfolge:</strong> Weiß zieht zuerst. Das Spiel wird dann gegen den Uhrzeigersinn fortgesetzt: Weiß → Schwarz → Grau.</li></ul>" },
            { title: "3. Das Spielbrett", content: "<ul><li>Das Spielbrett ist dreieckig.</li><li>Die zentralen Felder (die 'Festung') sind schwarz markiert und unpassierbar. Figuren können diese Felder weder überqueren noch darauf landen.</li></ul>" },
            { title: "4. Aufstellung der Figuren", content: "<ul><li><strong>Bauern:</strong> Beginnen das Spiel auf festen, vorbestimmten Positionen.</li><li><strong>Andere Figuren:</strong> Die Spieler setzen abwechselnd ihre restlichen Figuren (König, Dame, Türme, Läufer, Springer) in ihren jeweiligen Startzonen.</li></ul>" },
            { title: "5. Zugregeln der Figuren", content: "<ul><li><strong>König, Dame, Turm, Springer:</strong> Diese Figuren ziehen nach den Standardregeln des klassischen Schachs.</li><li><strong>Bauer:</strong> Hat einzigartige Bewegungsmöglichkeiten:<ul><li><strong>Bewegung (ohne Schlagen):</strong> Kann ein Feld vorwärts, seitwärts oder rückwärts ziehen. Der erste Zug eines Bauern kann ein oder zwei Felder vorwärts sein.</li><li><strong>Schlagen:</strong> Schlägt eine gegnerische Figur, indem er ein Feld diagonal in eine beliebige Richtung (vorwärts oder rückwärts) zieht.</li><li><strong>Umwandlung:</strong> Wenn ein Bauer eine gegnerische Umwandlungszone erreicht, muss er sofort in eine Dame, einen Turm, einen Läufer oder einen Springer derselben Farbe umgewandelt werden.</li></ul></li><li><strong>Läufer:</strong><ul><li><strong>Standardzug:</strong> Zieht eine beliebige Anzahl freier Felder diagonal, wie im klassischen Schach.</li><li><strong>Sonderzug (Diagonalwechsel):</strong> Ein Läufer kann ein Feld orthogonal (vorwärts, rückwärts oder seitwärts) ziehen, um auf eine andersfarbige Diagonale zu wechseln.</li><li><strong>Abklingzeit des Sonderzugs:</strong> Nachdem ein Läufer einen Sonderzug zum Diagonalwechsel gemacht hat, muss er mindestens einen normalen diagonalen Zug machen, bevor er erneut die Diagonale wechseln darf.</li></ul></li></ul>" },
            { title: "6. Schach, Schachmatt & Patt", content: "<ul><li><strong>Schach:</strong> Eine Position, in der ein König von einer gegnerischen Figur angegriffen wird. Der Spieler muss seinen König aus dem Schach bewegen.</li><li><strong>Schachmatt:</strong> Eine Situation, in der der König eines Spielers im Schach steht und es keine legalen Züge gibt, um dem Schach zu entkommen. Ein schachmatt gesetzter Spieler scheidet aus und alle seine Figuren werden vom Brett entfernt.</li><li><strong>Patt:</strong> Eine Situation, in der ein Spieler nicht im Schach steht, aber keine legalen Züge hat. Ein Spieler im Patt scheidet ebenfalls aus dem Spiel aus.</li><li>Das Spiel wird fortgesetzt, bis nur noch ein Spieler übrig ist.</li></ul>" },
            { title: "7. Bauernumwandlungszonen", content: "<p>Es gibt spezielle Felder auf dem Brett für die Bauernumwandlung. Wenn ein Umwandlungsfeld leer ist, ist es mit einem kleinen farbigen Kreis markiert, der der Farbe des Spielers entspricht, dessen Bauer auf diesem Feld umwandeln kann.</p>" },
            { title: "8. Figurenwerte (für Schlagen)", content: "<ul><li>Bauer: 1 Punkt</li><li>Springer: 3 Punkte</li><li>Läufer: 3 Punkte</li><li>Turm: 5 Punkte</li><li>Dame: 9 Punkte</li></ul>" },
        ]
    },
    fr: {
        title: "Règles du Jeu",
        sections: [
            { title: "1. Objectif", content: "<p>L'objectif du jeu est d'éliminer tous les adversaires en les mettant échec et mat. Le dernier joueur restant sur l'échiquier est déclaré vainqueur.</p>" },
            { title: "2. Joueurs & Ordre de Jeu", content: "<ul><li><strong>Joueurs :</strong> Il y a trois joueurs : Blanc (gauche), Noir (droite) et Gris (haut).</li><li><strong>Ordre de jeu :</strong> Les Blancs jouent en premier. Le jeu se poursuit ensuite dans le sens antihoraire : Blanc → Noir → Gris.</li></ul>" },
            { title: "3. L'Échiquier", content: "<ul><li>L'échiquier est de forme triangulaire.</li><li>Les cases centrales (la 'forteresse') sont marquées en noir et sont infranchissables. Les pièces ne peuvent ni traverser ni s'arrêter sur ces cases.</li></ul>" },
            { title: "4. Mise en Place des Pièces", content: "<ul><li><strong>Pions :</strong> Commencent la partie sur des positions fixes et prédéterminées.</li><li><strong>Autres pièces :</strong> Les joueurs placent à tour de rôle leurs pièces restantes (Roi, Dame, Tours, Fou, Cavalier) dans leurs zones de départ désignées.</li></ul>" },
            { title: "5. Mouvement des Pièces", content: "<ul><li><strong>Roi, Dame, Tour, Cavalier :</strong> Ces pièces se déplacent selon les règles standard des échecs classiques.</li><li><strong>Pion :</strong> Possède des capacités de mouvement uniques :<ul><li><strong>Mouvement (sans capture) :</strong> Peut se déplacer d'une case en avant, sur le côté ou en arrière. Le premier coup d'un pion peut être d'une ou deux cases en avant.</li><li><strong>Capture :</strong> Capture une pièce adverse en se déplaçant d'une case en diagonale dans n'importe quelle direction (vers l'avant ou vers l'arrière).</li><li><strong>Promotion :</strong> Lorsqu'un pion atteint une zone de promotion adverse, il doit être immédiatement promu en Dame, Tour, Fou ou Cavalier de la même couleur.</li></ul></li><li><strong>Fou :</strong><ul><li><strong>Mouvement standard :</strong> Se déplace d'un nombre quelconque de cases libres en diagonale, comme aux échecs classiques.</li><li><strong>Mouvement spécial (Changement de diagonale) :</strong> Un Fou peut se déplacer d'une case orthogonalement (en avant, en arrière ou sur le côté) pour passer à un ensemble de diagonales de couleur différente.</li><li><strong>Restriction du mouvement spécial :</strong> Après avoir effectué un mouvement spécial pour changer de diagonale, le Fou doit effectuer au moins un mouvement diagonal standard avant de pouvoir changer à nouveau de diagonale.</li></ul></li></ul>" },
            { title: "6. Échec, Échec et Mat & Pat", content: "<ul><li><strong>Échec :</strong> Une position où un Roi est attaqué par une pièce adverse. Le joueur doit effectuer un mouvement pour sortir son Roi de l'échec.</li><li><strong>Échec et Mat :</strong> Une situation où le Roi d'un joueur est en échec et il n'y a aucun coup légal pour échapper à l'échec. Un joueur mis échec et mat est éliminé et toutes ses pièces sont retirées de l'échiquier.</li><li><strong>Pat :</strong> Une situation où un joueur n'est pas en échec mais n'a aucun coup légal. Un joueur en situation de pat est également éliminé du jeu.</li><li>La partie continue jusqu'à ce qu'un seul joueur reste.</li></ul>" },
            { title: "7. Zones de Promotion des Pions", content: "<p>Il y a des cases spéciales sur l'échiquier pour la promotion des pions. Lorsqu'une case de promotion est vide, elle est marquée d'un petit cercle de couleur correspondant à la couleur du joueur dont le pion peut être promu sur cette case.</p>" },
            { title: "8. Valeur des Pièces (pour les captures)", content: "<ul><li>Pion : 1 point</li><li>Cavalier : 3 points</li><li>Fou : 3 points</li><li>Tour : 5 points</li><li>Dame : 9 points</li></ul>" },
        ]
    },
    es: {
        title: "Reglas del Juego",
        sections: [
            { title: "1. Objetivo", content: "<p>El objetivo del juego es eliminar a todos los oponentes dándoles jaque mate. El último jugador que quede en el tablero es declarado ganador.</p>" },
            { title: "2. Jugadores y Orden de Turno", content: "<ul><li><strong>Jugadores:</strong> Hay tres jugadores: Blanco (izquierda), Negro (derecha) y Gris (arriba).</li><li><strong>Orden de turno:</strong> El Blanco mueve primero. El juego procede en sentido antihorario: Blanco → Negro → Gris.</li></ul>" },
            { title: "3. El Tablero", content: "<ul><li>El tablero es de forma triangular.</li><li>Las casillas centrales (la 'fortaleza') están marcadas en negro y son intransitables. Las piezas no pueden moverse a través de ellas ni detenerse en ellas.</li></ul>" },
            { title: "4. Colocación de las Piezas", content: "<ul><li><strong>Peones:</strong> Comienzan el juego en posiciones fijas y predeterminadas.</li><li><strong>Otras piezas:</strong> Los jugadores se turnan para colocar sus piezas restantes (Rey, Dama, Torres, Alfil, Caballo) dentro de sus zonas de inicio designadas.</li></ul>" },
            { title: "5. Reglas de Movimiento de las Piezas", content: "<ul><li><strong>Rey, Dama, Torre, Caballo:</strong> Estas piezas se mueven según las reglas estándar del ajedrez clásico.</li><li><strong>Peón:</strong> Tiene capacidades de movimiento únicas:<ul><li><strong>Movimiento (sin captura):</strong> Puede moverse una casilla hacia adelante, hacia los lados o hacia atrás. El primer movimiento de un peón puede ser de una o dos casillas hacia adelante.</li><li><strong>Captura:</strong> Captura una pieza del oponente moviéndose una casilla en diagonal en cualquier dirección (hacia adelante o hacia atrás).</li><li><strong>Promoción:</strong> Cuando un peón llega a una zona de promoción del oponente, debe ser promocionado inmediatamente a Dama, Torre, Alfil o Caballo del mismo color.</li></ul></li><li><strong>Alfil:</strong><ul><li><strong>Movimiento estándar:</strong> Se mueve cualquier número de casillas vacías en diagonal, como en el ajedrez clásico.</li><li><strong>Movimiento especial (Cambio de diagonal):</strong> Un Alfil puede moverse una casilla ortogonalmente (hacia adelante, hacia atrás o hacia los lados) para cambiar a un conjunto de diagonales de diferente color.</li><li><strong>Restricción del movimiento especial:</strong> Después de realizar un movimiento especial para cambiar de diagonal, el Alfil debe realizar al menos un movimiento diagonal estándar antes de poder cambiar de diagonal nuevamente.</li></ul></li></ul>" },
            { title: "6. Jaque, Jaque Mate y Ahogado", content: "<ul><li><strong>Jaque:</strong> Una posición en la que un Rey está bajo ataque de una pieza oponente. El jugador debe hacer un movimiento para sacar a su Rey del jaque.</li><li><strong>Jaque Mate:</strong> Una situación en la que el Rey de un jugador está en jaque y no hay movimientos legales para escapar del jaque. Un jugador en jaque mate es eliminado y todas sus piezas se retiran del tablero.</li><li><strong>Ahogado (Stalemate):</strong> Una situación en la que un jugador no está en jaque pero no tiene movimientos legales. Un jugador en situación de ahogado también es eliminado del juego.</li><li>El juego continúa hasta que solo queda un jugador.</li></ul>" },
            { title: "7. Zonas de Promoción de Peones", content: "<p>Hay casillas especiales en el tablero para la promoción de peones. Cuando una casilla de promoción está vacía, se marca con un pequeño círculo de color que corresponde al color del jugador cuyo peón puede promocionar en esa casilla.</p>" },
            { title: "8. Valor de las Piezas (por capturas)", content: "<ul><li>Peón: 1 punto</li><li>Caballo: 3 puntos</li><li>Alfil: 3 puntos</li><li>Torre: 5 puntos</li><li>Dama: 9 puntos</li></ul>" },
        ]
    },
    it: {
        title: "Regole del Gioco",
        sections: [
            { title: "1. Obiettivo", content: "<p>L'obiettivo del gioco è eliminare tutti gli avversari dando loro scacco matto. L'ultimo giocatore rimasto sulla scacchiera è dichiarato vincitore.</p>" },
            { title: "2. Giocatori e Ordine di Turno", content: "<ul><li><strong>Giocatori:</strong> Ci sono tre giocatori: Bianco (sinistra), Nero (destra) e Grigio (in alto).</li><li><strong>Ordine di turno:</strong> Il Bianco muove per primo. Il gioco procede in senso antiorario: Bianco → Nero → Grigio.</li></ul>" },
            { title: "3. La Scacchiera", content: "<ul><li>La scacchiera è di forma triangolare.</li><li>Le caselle centrali (la 'fortezza') sono contrassegnate in nero e sono impraticabili. I pezzi non possono attraversarle o fermarsi su di esse.</li></ul>" },
            { title: "4. Posizionamento dei Pezzi", content: "<ul><li><strong>Pedoni:</strong> Iniziano il gioco in posizioni fisse e predeterminate.</li><li><strong>Altri pezzi:</strong> I giocatori, a turno, posizionano i loro pezzi rimanenti (Re, Regina, Torri, Alfiere, Cavallo) all'interno delle loro zone di partenza designate.</li></ul>" },
            { title: "5. Regole di Movimento dei Pezzi", content: "<ul><li><strong>Re, Regina, Torre, Cavallo:</strong> Questi pezzi si muovono secondo le regole standard degli scacchi classici.</li><li><strong>Pedone:</strong> Ha capacità di movimento uniche:<ul><li><strong>Movimento (senza cattura):</strong> Può muoversi di una casella in avanti, di lato o all'indietro. La prima mossa di un pedone può essere di una o due caselle in avanti.</li><li><strong>Cattura:</strong> Cattura un pezzo avversario muovendosi di una casella in diagonale in qualsiasi direzione (avanti o indietro).</li><li><strong>Promozione:</strong> Quando un pedone raggiunge una zona di promozione avversaria, deve essere immediatamente promosso a Regina, Torre, Alfiere o Cavallo dello stesso colore.</li></ul></li><li><strong>Alfiere:</strong><ul><li><strong>Mossa standard:</strong> Si muove di un qualsiasi numero di caselle libere in diagonale, come negli scacchi classici.</li><li><strong>Mossa speciale (Cambio di diagonale):</strong> Un Alfiere può muoversi di una casella ortogonalmente (avanti, indietro o di lato) per passare a un insieme di diagonali di colore diverso.</li><li><strong>Restrizione della mossa speciale:</strong> Dopo aver effettuato una mossa speciale per cambiare diagonale, l'Alfiere deve effettuare almeno una mossa diagonale standard prima di poter cambiare di nuovo diagonale.</li></ul></li></ul>" },
            { title: "6. Scacco, Scacco Matto e Stallo", content: "<ul><li><strong>Scacco:</strong> Una posizione in cui un Re è sotto attacco da un pezzo avversario. Il giocatore deve fare una mossa per togliere il proprio Re dallo scacco.</li><li><strong>Scacco Matto:</strong> Una situazione in cui il Re di un giocatore è sotto scacco e non ci sono mosse legali per sfuggire allo scacco. Un giocatore che subisce scacco matto viene eliminato e tutti i suoi pezzi vengono rimossi dalla scacchiera.</li><li><strong>Stallo:</strong> Una situazione in cui un giocatore non è sotto scacco ma non ha mosse legali. Anche un giocatore in stallo viene eliminato dal gioco.</li><li>Il gioco continua finché non rimane un solo giocatore.</li></ul>" },
            { title: "7. Zone di Promozione dei Pedoni", content: "<p>Ci sono caselle speciali sulla scacchiera per la promozione dei pedoni. Quando una casella di promozione è vuota, è contrassegnata da un piccolo cerchio colorato corrispondente al colore del giocatore il cui pedone può essere promosso su quella casella.</p>" },
            { title: "8. Valore dei Pezzi (per le catture)", content: "<ul><li>Pedone: 1 punto</li><li>Cavallo: 3 punti</li><li>Alfiere: 3 punti</li><li>Torre: 5 punti</li><li>Regina: 9 punti</li></ul>" },
        ]
    }
};
